global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'driver-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['driver-service:8083']

  - job_name: 'ride-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ride-service:8082']

  - job_name: 'location-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['location-service:8084']

  - job_name: 'matching-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['matching-service:8085']

  - job_name: 'websocket-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['websocket-service:8086']
